trigger:
  - main
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'id_rsa'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      mkdir -p ~/.ssh
      cp $(Agent.TempDirectory)/id_rsa ~/.ssh/id_rsa
      chmod 400 ~/.ssh/id_rsa
      ssh-keyscan -H 192.168.1.101 >> ~/.ssh/known_hosts
      ssh-keyscan -H 192.168.1.102 >> ~/.ssh/known_hosts
      ssh-keyscan -H 192.168.1.103 >> ~/.ssh/known_hosts
      sudo apt update
      sudo apt install -y ansible
      ansible-playbook -i inventory.yml test-playbook.yml -l myhost2
