name: Run Ansible Playbook
on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering via GitHub GUI
jobs:
  run-playbook:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: /home/runner/Postgres
      - name: Install Ansible dependencies
        run: |
          sudo dnf install -y ansible-core
      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i /home/runner/Postgres/inventory.yml /home/runner/Postgres/pgsql-01-init-binaries.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
