name: Run Ansible Playbook
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  run-playbook:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ansible dependencies
        run: |
          sudo dnf install -y ansible-core
      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible-postgres-playbooks/inventory.yml ansible-postgres-playbooks/pgsql-01-init-binaries.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
