name: Run Ansible Playbook
on:
  push:
    branches: [ main ]
jobs:
  run-playbook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
        ssh-keyscan -H 192.168.1.101 >> ~/.ssh/known_hosts
        ssh-keyscan -H 192.168.1.102 >> ~/.ssh/known_hosts
        ssh-keyscan -H 192.168.1.103 >> ~/.ssh/known_hosts
    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible
    - name: Run PostgreSQL Binaries Playbook
      run: ansible-playbook -i inventory.yml pgsql-01-init-binaries.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: False
